name: core
version: 0.0.1
publish_to: none
description: Project core module

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  navigation:
    path: ../navigation

  get_it: ^7.2.0
  dio: ^5.1.1
  logger: ^1.3.0
  flutter_bloc: ^8.1.3
  easy_localization: ^3.0.3
  bloc: ^8.1.2
  equatable: ^2.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  assets:
    - resources/langs/