name: auth
description: Home feature
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.1.1 <4.1.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core
  domain:
    path: ../../domain
  core_ui:
    path: ../../core_ui
  navigation:
    path: ../../navigation


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
